const FAISS_PREPARE_DIR = 'db';
const TONGYI_EMBEDDINGS_MODEL_NAME = 'tongyi-text-embedding-v2';
const FAISS_PREPARE_FILE_PATH = `${FAISS_PREPARE_DIR}/${TONGYI_EMBEDDINGS_MODEL_NAME}`;

module.exports = {
  FAISS_PREPARE_DIR,
  TONGYI_EMBEDDINGS_MODEL_NAME,
  FAISS_PREPARE_FILE_PATH,
};
